// This comment block was generated by running the following command:
// go generate
// DO NOT EDIT.
//go:build wasm
// +build wasm


package buttons

import "syscall/js"

func Begin_Interactivity() {
	document := js.Global().Get("document")
	element := document.Call("getElementById", "button1")
	element.Set("innerText", "Updated content from Go!")
	element.Set("onclick", js.FuncOf(func(this js.Value, p []js.Value) interface{} {
		js.Global().Call("alert", "Button clicked!")
		return nil
	}))

}
