.PHONY: all
BUILD_PLATFORM=
BUILD_ARCH=

ifeq ($(OS),Windows_NT)
	BUILD_PLATFORM = WIN32
	ifeq ($(PROCESSOR_ARCHITEW6432),AMD64)
		BUILD_ARCH = AMD64
	else
	ifeq ($(PROCESSOR_ARCHITECTURE),AMD64)
		BUILD_ARCH = AMD64
	endif
	ifeq ($(PROCESSOR_ARCHITECTURE),x86)
		BUILD_ARCH = IA32
	endif
endif
else
	UNAME_S := $(shell uname -s)
	ifeq ($(UNAME_S),Linux)
		BUILD_PLATFORM = LINUX
	endif
	ifeq ($(UNAME_S),Darwin)
		BUILD_PLATFORM = OSX
	endif
	UNAME_P := $(shell uname -p)
	ifeq ($(UNAME_P),x86_64)
		BUILD_ARCH = AMD64
	endif
	ifneq ($(filter %86,$(UNAME_P)),)
		BUILD_ARCH = IA32
	endif
	ifneq ($(filter arm%,$(UNAME_P)),)
		BUILD_ARCH = ARM
	endif
	UNAME_P = $(shell uname -m)
	ifeq ($(UNAME_P),x86_64)
		BUILD_ARCH = AMD64
	endif
	ifneq ($(filter %86,$(UNAME_P)),)
		BUILD_ARCH = IA32
	endif
endif

all:
	@echo "The operating system of this system is: $(BUILD_PLATFORM)"
	@echo "The processor architecture of this system is: $(BUILD_ARCH)"
#mkdir check
