// This comment block was generated by running the following command:
// go generate
// DO NOT EDIT.
package main

// This file is a stub
// This is for the handlers.go file that was moved and modularized into the hooks/pages directory.
// Moved to /src/hooks/pages/**